// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telemetry.Api.Infrastructure.Persistence;

#nullable disable

namespace Telemetry.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618112305_AddLogRecord")]
    partial class AddLogRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telemetry.Api.Domain.Models.EventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("_id");

                    b.Property<bool?>("Cancellable")
                        .HasColumnType("bit")
                        .HasColumnName("cancellable");

                    b.Property<bool?>("Cancelled")
                        .HasColumnType("bit")
                        .HasColumnName("cancelled");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("docid");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("docpath");

                    b.Property<string>("DocumentTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("doctemplate");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("doctype");

                    b.Property<string>("EventArgs")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("args");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("handler_id");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("host_user");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("projectname");

                    b.Property<string>("ProjectNum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("projectnum");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revit");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.LogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("_id");

                    b.Property<string>("EnvironmentMachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("env_machinename");

                    b.Property<string>("EnvironmentUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("env_username");

                    b.Property<string>("Exception")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exception");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("log_level");

                    b.Property<string>("LogEvent")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("log_event");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_template");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plugin_name");

                    b.Property<Guid>("PluginSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("plugin_session_id");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rendered_message");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revit_build");

                    b.Property<string>("RevitDocumentModelPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("doc_modelpath");

                    b.Property<string>("RevitDocumentPathName")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("doc_pathname");

                    b.Property<string>("RevitDocumentTitle")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("doc_title");

                    b.Property<string>("RevitLanguage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revit_language");

                    b.Property<string>("RevitUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revit_username");

                    b.Property<int>("RevitVersion")
                        .HasColumnType("int")
                        .HasColumnName("revit_version");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.ScriptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("_id");

                    b.Property<string>("CloneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("clone");

                    b.Property<string>("CommandBundle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("commandbundle");

                    b.Property<string>("CommandExtension")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("commandextension");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("commandname");

                    b.Property<string>("CommandResults")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commandresults");

                    b.Property<string>("CommandUniqueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("commanduniquename");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("docname");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("docpath");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exec_id");

                    b.Property<DateTimeOffset>("ExecTimestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("exec_timestamp");

                    b.Property<string>("HostUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("host_user");

                    b.Property<bool>("IsConfig")
                        .HasColumnType("bit")
                        .HasColumnName("config");

                    b.Property<bool>("IsDebug")
                        .HasColumnType("bit")
                        .HasColumnName("debug");

                    b.Property<bool>("IsExecFromGui")
                        .HasColumnType("bit")
                        .HasColumnName("from_gui");

                    b.Property<string>("PyRevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pyrevit");

                    b.Property<int>("ResultCode")
                        .HasColumnType("int")
                        .HasColumnName("resultcode");

                    b.Property<string>("RevitBuild")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revitbuild");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("revit");

                    b.Property<string>("ScriptPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("scriptpath");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sessionid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("scripts");
                });

            modelBuilder.Entity("Telemetry.Api.Domain.Models.ScriptRecord", b =>
                {
                    b.OwnsOne("Telemetry.Api.Domain.Models.TraceInfo", "Trace", b1 =>
                        {
                            b1.Property<Guid>("ScriptRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("message");

                            b1.HasKey("ScriptRecordId");

                            b1.ToTable("scripts");

                            b1.WithOwner()
                                .HasForeignKey("ScriptRecordId");

                            b1.OwnsOne("Telemetry.Api.Domain.Models.EngineInfo", "Engine", b2 =>
                                {
                                    b2.Property<Guid>("TraceInfoScriptRecordId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Configs")
                                        .HasMaxLength(8000)
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("configs");

                                    b2.PrimitiveCollection<string>("SysPaths")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("syspath");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("type");

                                    b2.Property<string>("Version")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("version");

                                    b2.HasKey("TraceInfoScriptRecordId");

                                    b2.ToTable("scripts");

                                    b2.WithOwner()
                                        .HasForeignKey("TraceInfoScriptRecordId");
                                });

                            b1.Navigation("Engine")
                                .IsRequired();
                        });

                    b.Navigation("Trace")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
