services:
  telemetry-api:
    container_name: telemetry-api
    image: ghcr.io/Bim4Everyone/b4e-telemetry:2.0.0
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
